version: "3.9"

services:
  razlivalka_django:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
    - 8000:8000
    volumes:
      - ./:/var/app
    depends_on:
      - database_django

  database_django:
    image: library/postgres:13.2
    volumes:
      - ./razlivalka/pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

