# Generated by Django 3.2 on 2021-04-22 23:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=40)),
                ('state', models.CharField(default='Production', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('hardware_model', models.CharField(blank=True, max_length=40, null=True)),
                ('network_role', models.CharField(blank=True, max_length=40, null=True)),
                ('org_unit', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
